"Tipsy-ness" level selector
Quaffel/get-me-drunk-efficiently pull request #14
Opened 2021-03-22 23:14 UTC by Quaffel

Any feedback on the overall concept/design is highly appreciated. 

This approach might be a little over-engineered, but it's quite robust and extremely customizable. If you have any suggestions on how this may be solved in a _much_ simpler way, however, please don't hesitate to share them with me.

Regarding the color scheme: As @lenaalaugh is working on a new design, I didn't mind leaving the primary color as-is.

Resolves #13.

2021-03-22 23:45 UTC, Quaffel commented
@Jonasdoubleyou Haven't tested it on mobile or other low-power devices yet. Would be great if you could re-deploy once the PR is merged. There are still a few things we could tweak in case we're running into performance problems...

2021-03-23 08:37 UTC, Jonasdoubleyou approved these changes
looks good

2021-03-23 13:41 UTC, lenaalaugh requested changes
All in all very good. However, please remove the unused import DegreeAngle in circleselector.tsx

2021-03-23 13:57 UTC, Jonasdoubleyou commented
If you are at it, you could also just add it to the form @Quaffel

2021-03-23 20:15 UTC, Jonasdoubleyou approved these changes

2021-03-24 10:58 UTC, lenaalaugh approved these changes

2021-03-24 11:09 UTC, merged

2021-03-24 11:18 UTC, Jonasdoubleyou commented
> @Jonasdoubleyou Haven't tested it on mobile or other low-power devices yet. Would be great if you could re-deploy once the PR is merged. There are still a few things we could tweak in case we're running into performance problems...

@Quaffel https://drunk.wilms.ninja/

2021-03-24 11:22 UTC, Jonasdoubleyou commented on frontend/src/tipsyselector/circleselector.tsx
> +            event.clientX - targetDimensionsInViewport.left,
@Quaffel Ah, missed this: the [TouchEvent](https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent) does not have a clientX and clientY. Instead you need to access `.touches[0]`, see [here](https://developer.mozilla.org/en-US/docs/Web/API/Touch/clientX)

2021-03-24 11:24 UTC, Quaffel commented
@Jonasdoubleyou Thanks for the heads-up and the deployment. I'll come up with a fix.